import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LanguageContext = createContext({
  language: 'vi',
  setLanguage: () => {},
  t: (key, fallback) => fallback || key,
});

const messages = {
  vi: {
    // Header & Navigation
    brandTagline: 'Ngân hàng ưu tiên',
    backHome: 'Về trang chủ',
    quickNav: 'Điều hướng nhanh',
    dashboard: 'Tổng quan',
    transactions: 'Giao dịch',
    categories: 'Danh mục',
    budgets: 'Ngân sách',
    goals: 'Mục tiêu',
    debts: 'Quản lý nợ',
    statistics: 'Thống kê',
    account: 'Tài khoản',
    user: 'Người dùng',
    profile: 'Hồ sơ',
    logout: 'Thoát',
    home: 'Trang chủ',
    settings: 'Cài đặt',
    notifications: 'Thông báo',
    markRead: 'Đánh dấu đã đọc',
    noNotifications: 'Không có thông báo mới',
    themeMode: 'Chế độ nền',
    modeActive: 'Đang dùng',
    darkMode: 'Dark mode',
    lightMode: 'Light mode',
    language: 'Ngôn ngữ',
    languageDesc: 'Chọn ngôn ngữ hiển thị cho ứng dụng',
    languageVi: 'Tiếng Việt',
    languageEn: 'English',
    accountProfile: 'Hồ sơ tài khoản',
    privacy: 'Quyền riêng tư',
    support: 'Hỗ trợ & liên hệ',
    languageSaved: 'Ngôn ngữ được lưu tự động',
    addTransaction: 'Thêm Giao dịch',
    
    // Dashboard
    goodMorning: 'Chào buổi sáng',
    goodAfternoon: 'Chào buổi chiều',
    goodEvening: 'Chào buổi tối',
    balanceTitle: 'Số dư',
    monthlyIncome: 'Thu nhập hàng tháng',
    monthlyExpense: 'Chi tiêu hàng tháng',
    savingsRate: 'Tỷ lệ tiết kiệm',
    monthlyComparison: '% so với tháng trước',
    goalProgress: 'Tiến độ mục tiêu',
    viewAll: 'Xem tất cả',
    noGoals: 'Bạn chưa có mục tiêu nào.',
    intelligentSuggestion: 'Gợi ý thông minh',
    defaultSuggestion: 'Bạn có thể tiết kiệm thêm nếu giữ mức chi tiêu hiện tại.',
    expenseForecast: 'Dự báo chi tiêu',
    currentExpense: 'Chi tiêu hiện tại',
    forecastedExpense: 'Chi tiêu dự báo',
    topCategories: 'Top Danh mục',
    categoryShare: 'Tỷ trọng',
    today: 'hôm nay',
    thisWeek: 'tuần này',
    thisMonth: 'tháng này',
    thisYear: 'năm nay',
    
    // Transactions
    transactionList: 'Danh sách giao dịch',
    transactionCalendar: 'Lịch giao dịch',
    listView: 'Danh sách',
    calendarView: 'Lịch',
    filter: 'Bộ lọc',
    search: 'Tìm kiếm',
    advanced: 'Nâng cao',
    export: 'Xuất',
    import: 'Nhập',
    type: 'Loại',
    category: 'Danh mục',
    date: 'Ngày',
    amount: 'Số tiền',
    from: 'Từ',
    to: 'Đến',
    income: 'Thu nhập',
    expense: 'Chi tiêu',
    all: 'Tất cả',
    clearFilters: 'Xóa bộ lọc',
    edit: 'Sửa',
    delete: 'Xóa',
    confirm: 'Xác nhận',
    deleteConfirm: 'Bạn có chắc chắn muốn xóa giao dịch này?',
    
    // Categories
    categoryManagement: 'Quản lý danh mục',
    totalCategories: 'Danh mục',
    default: 'Mặc định',
    custom: 'Tùy chỉnh',
    categoryDistribution: 'Phân bổ danh mục',
    incomeCategoriesOnly: 'Chỉ thu nhập',
    expenseCategoriesOnly: 'Chỉ chi tiêu',
    bothTypes: 'Cả hai',
    cannotDeleteDefault: 'Không thể xóa danh mục mặc định',
    deleteCategory: 'Xóa danh mục',
    incomeCategory: 'Danh mục thu nhập',
    expenseCategory: 'Danh mục chi tiêu',
    bothCategory: 'Dùng cho cả hai',
    
    // Budgets
    budgetManagement: 'Quản lý ngân sách',
    totalBudget: 'Ngân sách',
    budgetUsed: '% ngân sách đã sử dụng',
    spent: 'Đã chi tiêu',
    remaining: 'Còn lại',
    overspent: 'Vượt ngân sách',
    budgetProgress: 'Tiến độ ngân sách',
    budgetStatus: {
      ok: 'Ổn',
      warning: 'Sắp vượt',
      over: 'Vượt ngân sách',
    },
    period: {
      monthly: 'Tháng',
      weekly: 'Tuần',
      yearly: 'Năm',
    },
    overBudget: 'Vượt ngân sách',
    deleteBudgetConfirm: 'Xóa ngân sách',
    budgetPlaceholder: 'Tổng chi tiêu',
    
    // Goals
    goalTitle: 'Mục tiêu tài chính',
    targetAmount: 'Mục tiêu',
    currentAmount: 'Đang tích lũy',
    goalDeadline: 'Hạn chót',
    goalCompletion: 'Tiến độ hoàn thành',
    goalPriority: 'Ưu tiên',
    priorityHigh: 'Cao',
    priorityMedium: 'Trung bình',
    priorityLow: 'Thấp',
    daysRemaining: 'Còn lại',
    daysOverdue: 'Quá hạn',
    goalToday: 'Hôm nay',
    oneDay: 'Còn 1 ngày',
    inDays: 'Còn {days} ngày',
    goalActive: 'Đang hoạt động',
    goalAchieved: 'Đã hoàn thành',
    deleteGoalConfirm: 'Bạn có chắc chắn muốn xóa mục tiêu này?',
    goalAchievedMsg: '🎉 Mục tiêu đã được hoàn thành!',
    addGoalAmount: 'Thêm số tiền',
    goalsEmpty: 'Bạn chưa có mục tiêu nào.',
    
    // Debts
    debtManagement: 'Quản lý công nợ',
    netBalance: 'Cân bằng ròng',
    positive: 'Vị thế dương',
    negative: 'Vị thế âm',
    youAreOwed: 'Bạn được nợ nhiều hơn',
    youOwe: 'Bạn nợ nhiều hơn',
    lendingAmount: 'Người khác nợ tôi',
    borrowingAmount: 'Tôi đang nợ',
    settled: 'Đã tất toán',
    debtPaymentProgress: 'Tiến độ trả nợ',
    noDebts: 'Bạn chưa có khoản nợ nào.',
    deleteDebtConfirm: 'Xóa khoản nợ',
    addDebt: 'Thêm khoản nợ',
    paymentRecord: 'Lịch sử thanh toán',
    
    // Profile
    accountPage: 'Tài khoản',
    profilePage: 'Hồ sơ',
    fullName: 'Tên đầy đủ',
    email: 'Email',
    defaultBudget: 'Ngân sách mặc định',
    currency: 'Tiền tệ',
    avatar: 'Ảnh đại diện',
    uploadAvatar: 'Tải lên ảnh đại diện',
    saveProfile: 'Lưu hồ sơ',
    changePassword: 'Đổi mật khẩu',
    currentPassword: 'Mật khẩu hiện tại',
    newPassword: 'Mật khẩu mới',
    confirmPassword: 'Xác nhận mật khẩu',
    save: 'Lưu',
    cancel: 'Hủy',
    passwordMismatch: 'Mật khẩu xác nhận không khớp',
    passwordMinLength: 'Mật khẩu mới phải có ít nhất 6 ký tự',
    fileSizeError: 'Ảnh không được vượt quá 5MB',
    fileTypeError: 'Vui lòng chọn file hình ảnh',
    
    // Statistics
    statisticsLabel: 'Thống kê',
    overviewTab: 'Tổng quan',
    compareTab: 'So sánh',
    forecastTab: 'Dự báo',
    trendsTab: 'Xu hướng',
    dailyTab: 'Theo ngày',
    totalIncome: 'Tổng thu nhập',
    totalExpense: 'Tổng chi tiêu',
    netSavings: 'Tiết kiệm ròng',
    statsPeriod: 'Kỳ',
    sixMonths: '6 tháng',
    averageMonthlyIncome: 'TB thu nhập/tháng',
    averageMonthlyExpense: 'TB chi tiêu/tháng',
    forecastExpense: 'Chi tiêu dự báo',
    confidence: 'Độ tin cậy',
    
    // Landing Page
    featuredArtwork: 'Dòng tiền thịnh vượng',
    artworkSubtitle: 'Kỷ luật tạo nên tự do tài chính',
    hero_title: 'Quản lý tài chính thông minh',
    hero_desc: 'Kiểm soát chi tiêu, đạt mục tiêu, và xây dựng tương lai tài chính của bạn',
    cta_button: 'Bắt đầu',
    features: 'Tính năng',
    pricing: 'Giá',
    about: 'Về chúng tôi',
    contact: 'Liên hệ',
    
    // Auth
    login: 'Đăng nhập',
    register: 'Đăng ký',
    forgotPassword: 'Quên mật khẩu?',
    password: 'Mật khẩu',
    rememberMe: 'Ghi nhớ tôi',
    dontHaveAccount: 'Bạn chưa có tài khoản?',
    alreadyHaveAccount: 'Bạn đã có tài khoản?',
    signUp: 'Đăng ký',
    signIn: 'Đăng nhập',
  },
  en: {
    // Header & Navigation
    brandTagline: 'Priority banking',
    backHome: 'Back to home',
    quickNav: 'Quick navigation',
    dashboard: 'Overview',
    transactions: 'Transactions',
    categories: 'Categories',
    budgets: 'Budgets',
    goals: 'Goals',
    debts: 'Debt management',
    statistics: 'Statistics',
    account: 'Account',
    user: 'User',
    profile: 'Profile',
    logout: 'Logout',
    home: 'Home',
    settings: 'Settings',
    notifications: 'Notifications',
    markRead: 'Mark all as read',
    noNotifications: 'No new notifications',
    themeMode: 'Theme mode',
    modeActive: 'Current',
    darkMode: 'Dark mode',
    lightMode: 'Light mode',
    language: 'Language',
    languageDesc: 'Choose your application display language',
    languageVi: 'Vietnamese',
    languageEn: 'English',
    accountProfile: 'Account profile',
    privacy: 'Privacy',
    support: 'Support & contact',
    languageSaved: 'Language is saved automatically',
    addTransaction: 'Add transaction',
    
    // Dashboard
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    balanceTitle: 'Balance',
    monthlyIncome: 'Monthly income',
    monthlyExpense: 'Monthly expense',
    savingsRate: 'Savings rate',
    monthlyComparison: '% compared to last month',
    goalProgress: 'Goal progress',
    viewAll: 'View all',
    noGoals: 'You don\'t have any goals yet.',
    intelligentSuggestion: 'Intelligent suggestion',
    defaultSuggestion: 'You can save more by maintaining your current spending level.',
    expenseForecast: 'Expense forecast',
    currentExpense: 'Current expense',
    forecastedExpense: 'Forecasted expense',
    topCategories: 'Top categories',
    categoryShare: 'Share',
    today: 'today',
    thisWeek: 'this week',
    thisMonth: 'this month',
    thisYear: 'this year',
    
    // Transactions
    transactionList: 'Transaction list',
    transactionCalendar: 'Transaction calendar',
    listView: 'List',
    calendarView: 'Calendar',
    filter: 'Filter',
    search: 'Search',
    advanced: 'Advanced',
    export: 'Export',
    import: 'Import',
    type: 'Type',
    category: 'Category',
    date: 'Date',
    amount: 'Amount',
    from: 'From',
    to: 'To',
    income: 'Income',
    expense: 'Expense',
    all: 'All',
    clearFilters: 'Clear filters',
    edit: 'Edit',
    delete: 'Delete',
    confirm: 'Confirm',
    deleteConfirm: 'Are you sure you want to delete this transaction?',
    
    // Categories
    categoryManagement: 'Category management',
    totalCategories: 'Categories',
    default: 'Default',
    custom: 'Custom',
    categoryDistribution: 'Category distribution',
    incomeCategoriesOnly: 'Income only',
    expenseCategoriesOnly: 'Expense only',
    bothTypes: 'Both',
    cannotDeleteDefault: 'Cannot delete default category',
    deleteCategory: 'Delete category',
    incomeCategory: 'Income category',
    expenseCategory: 'Expense category',
    bothCategory: 'Used for both',
    
    // Budgets
    budgetManagement: 'Budget management',
    totalBudget: 'Budget',
    budgetUsed: '% budget used',
    spent: 'Spent',
    remaining: 'Remaining',
    overspent: 'Overspent',
    budgetProgress: 'Budget progress',
    budgetStatus: {
      ok: 'OK',
      warning: 'Warning',
      over: 'Over budget',
    },
    period: {
      monthly: 'Monthly',
      weekly: 'Weekly',
      yearly: 'Yearly',
    },
    overBudget: 'Over budget',
    deleteBudgetConfirm: 'Delete budget',
    budgetPlaceholder: 'Total spending',
    
    // Goals
    goalTitle: 'Financial goals',
    targetAmount: 'Target',
    currentAmount: 'Currently saving',
    goalDeadline: 'Deadline',
    goalCompletion: 'Overall completion',
    goalPriority: 'Priority',
    priorityHigh: 'High',
    priorityMedium: 'Medium',
    priorityLow: 'Low',
    daysRemaining: 'Remaining',
    daysOverdue: 'Overdue',
    goalToday: 'Today',
    oneDay: '1 day remaining',
    inDays: '{days} days remaining',
    goalActive: 'Active',
    goalAchieved: 'Achieved',
    deleteGoalConfirm: 'Are you sure you want to delete this goal?',
    goalAchievedMsg: '🎉 Goal has been achieved!',
    addGoalAmount: 'Add amount',
    goalsEmpty: 'You don\'t have any goals yet.',
    
    // Debts
    debtManagement: 'Debt management',
    netBalance: 'Net balance',
    positive: 'Positive position',
    negative: 'Negative position',
    youAreOwed: 'You are owed more',
    youOwe: 'You owe more',
    lendingAmount: 'Others owe me',
    borrowingAmount: 'I owe',
    settled: 'Settled',
    debtPaymentProgress: 'Payment progress',
    noDebts: 'You don\'t have any debts yet.',
    deleteDebtConfirm: 'Delete debt',
    addDebt: 'Add debt',
    paymentRecord: 'Payment history',
    
    // Profile
    accountPage: 'Account',
    profilePage: 'Profile',
    fullName: 'Full name',
    email: 'Email',
    defaultBudget: 'Default budget',
    currency: 'Currency',
    avatar: 'Avatar',
    uploadAvatar: 'Upload avatar',
    saveProfile: 'Save profile',
    changePassword: 'Change password',
    currentPassword: 'Current password',
    newPassword: 'New password',
    confirmPassword: 'Confirm password',
    save: 'Save',
    cancel: 'Cancel',
    passwordMismatch: 'Confirm password doesn\'t match',
    passwordMinLength: 'New password must be at least 6 characters',
    fileSizeError: 'Image must not exceed 5MB',
    fileTypeError: 'Please select an image file',
    
    // Statistics
    statisticsLabel: 'Statistics',
    overviewTab: 'Overview',
    compareTab: 'Compare',
    forecastTab: 'Forecast',
    trendsTab: 'Trends',
    dailyTab: 'Daily',
    totalIncome: 'Total income',
    totalExpense: 'Total expense',
    netSavings: 'Net savings',
    statsPeriod: 'Period',
    sixMonths: '6 months',
    averageMonthlyIncome: 'Avg income/month',
    averageMonthlyExpense: 'Avg expense/month',
    forecastExpense: 'Forecasted expense',
    confidence: 'Confidence',
    
    // Landing Page
    featuredArtwork: 'Prosperous cash flow',
    artworkSubtitle: 'Discipline creates financial freedom',
    hero_title: 'Smart financial management',
    hero_desc: 'Control your spending, achieve your goals, and build your financial future',
    cta_button: 'Get started',
    features: 'Features',
    pricing: 'Pricing',
    about: 'About us',
    contact: 'Contact',
    
    // Auth
    login: 'Login',
    register: 'Register',
    forgotPassword: 'Forgot password?',
    password: 'Password',
    rememberMe: 'Remember me',
    dontHaveAccount: 'Don\'t have an account?',
    alreadyHaveAccount: 'Already have an account?',
    signUp: 'Sign up',
    signIn: 'Sign in',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => localStorage.getItem('app-language') || 'vi');

  useEffect(() => {
    localStorage.setItem('app-language', language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(() => {
    const t = (key, fallback) => messages[language]?.[key] || fallback || key;
    return { language, setLanguage, t };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  return useContext(LanguageContext);
};
